apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: hello-k8s
        image: sangerusofficial/hello-k8s:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
        ports:
        - containerPort: 5000
